init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "4"
platform:
  - x86
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install

build: off

test_script:
  - node --version && npm --version
  - cmd: npm test
cache:
  - node_modules -> package.json